#!/bin/sh

module load Nextflow/20.12.0-edge
module load Singularity/3.6.4

#WORK=/camp/stp/babs/scratch/bahn
#WORK+=/032_spatial_transcriptomics
#WORK+=/work
WORK=work

nextflow run main.nf \
	-params-file params.yml \
	-work-dir $WORK \
	-resume

