#!/bin/sh

sudo docker build --tag bahnk/python:v1 .
sudo docker build --no-cache --tag bahnk/python:v1 .
sudo docker login -u "bahnk" -p "" docker.io
sudo docker push bahnk/python:v1
singularity pull sequencing.sif docker://bahnk/python:v1

