#!/bin/sh

sudo docker build --no-cache --tag sequencing:v1 .
sudo docker image tag sequencing:v1 bahnk/sequencing:v1
sudo docker login -u "bahnk" -p "" docker.io
sudo docker push bahnk/sequencing:v1

